### PR TITLE
Update Developer Guide

### PR DESCRIPTION
**Pull request by joytqt-1202**
Add Use Case, NFRs and Glossary

### CODE REVIEW

**Comment by shaowi** [comment]
Please merge my use cases, NFR and glossary with urs.

[t.md](https://github.com/AY2223S2-CS2103-F10-2/tp/files/10836144/t.md)

**Review by shaowi — COMMENTED** [review]
LGTM, i guess u can merge it after @lennoxtr include his

**Comment by lennoxtr** [comment]
LGTM

**Review by lennoxtr — APPROVED** [review]
LGTM

**Review by hingen — APPROVED** [review]
LGTM

**Pull request merged**
